variables:
  GIT_SUBMODULE_STRATEGY: recursive

.build_template: &build_definition
  stage: build
  script:
    - mkdir -p globalizer/share/minizinc/{globalizer,solvers}
    - stack --stack-root ${CI_PROJECT_DIR}/stack --work-dir build --local-bin-path globalizer/bin build --copy-bins --verbose
    - cp -r mznlib/globalizer globalizer/share/minizinc
    - cp globalizer.msc globalizer/share/minizinc/solvers/
  artifacts:
    paths:
      - globalizer
  cache:
    key: "${MZNARCH}_${CI_COMMIT_REF_SLUG}"
    paths:
      - build/
      - stack/

build:linux:
  <<: *build_definition
  image: haskell:8.2
  variables:
    MZNARCH: "linux"
  tags: [linux, docker, high-mem]

build:osx:
  <<: *build_definition
  variables:
    MZNARCH: "osx"
  before_script:
    - 'echo arch: x86_64 >> stack.yaml'
  tags: [osx, haskell, stack]

build:win64:
  <<: *build_definition
  variables:
    MZNARCH: "win64"
  before_script:
    - 'echo local-programs-path: %CI_PROJECT_DIR%\stack\programs >> stack.yaml'
  script:
    - stack --stack-root %CI_PROJECT_DIR%\stack exec -- mkdir -p globalizer/share/minizinc/globalizer
    - stack --stack-root %CI_PROJECT_DIR%\stack exec -- mkdir -p globalizer/share/minizinc/solvers
    - stack --stack-root %CI_PROJECT_DIR%\stack --work-dir build --local-bin-path globalizer\bin build --copy-bins --verbose
    - stack --stack-root %CI_PROJECT_DIR%\stack exec -- cp -r mznlib/globalizer globalizer/share/minizinc
    - stack --stack-root %CI_PROJECT_DIR%\stack exec -- cp globalizer.msc globalizer/share/minizinc/solvers/
  tags: [win64, haskell, stack]
